//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EventsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventSystem.Web.Resources.EventsResource", typeof(EventsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави лекция.
        /// </summary>
        public static string AddLecture {
            get {
                return ResourceManager.GetString("AddLecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неуспешно добавена лекция! Моля опитайте пак..
        /// </summary>
        public static string AddLectureFailure {
            get {
                return ResourceManager.GetString("AddLectureFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно добавена лекция за конкретния курс!.
        /// </summary>
        public static string AddLectureSuccess {
            get {
                return ResourceManager.GetString("AddLectureSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не можете да триете съдържание от събитие, на което не сте автор!.
        /// </summary>
        public static string DeleteEventContentNotAuthor {
            get {
                return ResourceManager.GetString("DeleteEventContentNotAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неуспешно изтрита лекция. Моля опитайте по-късно..
        /// </summary>
        public static string DeleteLectureFailure {
            get {
                return ResourceManager.GetString("DeleteLectureFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно изтрита лекция!.
        /// </summary>
        public static string DeleteLectureSuccess {
            get {
                return ResourceManager.GetString("DeleteLectureSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вие успешно се записахте за това събитие!.
        /// </summary>
        public static string EventEnrolled {
            get {
                return ResourceManager.GetString("EventEnrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вие нямате право да участвате на това събитие!.
        /// </summary>
        public static string EventExpelled {
            get {
                return ResourceManager.GetString("EventExpelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на събитието.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Събитието не е намерено..
        /// </summary>
        public static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вие не сте част от това събитие!.
        /// </summary>
        public static string EventNotPart {
            get {
                return ResourceManager.GetString("EventNotPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вие вече сте преминали това събитие!.
        /// </summary>
        public static string EventPassed {
            get {
                return ResourceManager.GetString("EventPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вие успешно се отписахте от това събитие!.
        /// </summary>
        public static string EventUnenrolled {
            get {
                return ResourceManager.GetString("EventUnenrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неуспешно изключване на човек. Моля опитайте по-късно..
        /// </summary>
        public static string ExpellUserFailure {
            get {
                return ResourceManager.GetString("ExpellUserFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно изключване на човек!.
        /// </summary>
        public static string ExpellUserSuccess {
            get {
                return ResourceManager.GetString("ExpellUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете дата на лекцията.
        /// </summary>
        public static string LectureDatePlaceholder {
            get {
                return ResourceManager.GetString("LectureDatePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание на лекцията.
        /// </summary>
        public static string LectureDescription {
            get {
                return ResourceManager.GetString("LectureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете описание на лекция.
        /// </summary>
        public static string LectureDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("LectureDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лекции.
        /// </summary>
        public static string Lectures {
            get {
                return ResourceManager.GetString("Lectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподавател.
        /// </summary>
        public static string LectureTeacher {
            get {
                return ResourceManager.GetString("LectureTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете преподавател за лекцията.
        /// </summary>
        public static string LectureTeacherPlaceholder {
            get {
                return ResourceManager.GetString("LectureTeacherPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на лекцията.
        /// </summary>
        public static string LectureTitle {
            get {
                return ResourceManager.GetString("LectureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете име на лекция.
        /// </summary>
        public static string LectureTitlePlaceholder {
            get {
                return ResourceManager.GetString("LectureTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете описание на събитието..
        /// </summary>
        public static string RequiredDescription {
            get {
                return ResourceManager.GetString("RequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете дата на провеждане на лекцията..
        /// </summary>
        public static string RequiredLectureDate {
            get {
                return ResourceManager.GetString("RequiredLectureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете описание на лекцията..
        /// </summary>
        public static string RequiredLectureDescription {
            get {
                return ResourceManager.GetString("RequiredLectureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете преподавател за лекцията..
        /// </summary>
        public static string RequiredLectureTeacher {
            get {
                return ResourceManager.GetString("RequiredLectureTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете име на лекцията..
        /// </summary>
        public static string RequiredLectureTitle {
            get {
                return ResourceManager.GetString("RequiredLectureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете заглавие на събитието..
        /// </summary>
        public static string RequiredTitle {
            get {
                return ResourceManager.GetString("RequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете тип на събитието..
        /// </summary>
        public static string RequiredType {
            get {
                return ResourceManager.GetString("RequiredType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете събитие.
        /// </summary>
        public static string SelectEvent {
            get {
                return ResourceManager.GetString("SelectEvent", resourceCulture);
            }
        }
    }
}
